site_name: Documentação da Atividade
site_author: Kelvin
site_dir: /var/www/html/tsi5/doc/kelvin/instalacao-config-mkdocs-wordpress

theme:
    name: material

nav:
    - Home: index.md
    - Instalação e Configuração: instalacao-configuracao.md
    - MkDocs: mkdocs.md
    - WordPress: wordpress.md
    - Referências: referencias.md
